
name: workflow-1
on: [push]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "Hello World"
      - name: step-2
        run: | 
          node -v
          npm -v