
name: workflow-1
on: [push]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "Hello World"
      - name: step-2
        run: | 
          node -v
          npm -v
  job-2:
    runs-on: windows-latest
    steps:
      - name: get ip address
        run: ipconfig